services:
  mysql:
    image: mysql:8.0
    container_name: crud-clientes-mysql
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    command: --default-authentication-plugin=caching_sha2_password

  backend:
    build: ./backend
    container_name: crud-clientes-backend
    restart: always
    ports:
      - '3000:3000'
    env_file:
      - ./backend/.env
    depends_on:
      - mysql

volumes:
  mysql_data:
