
FROM node:22-alpine 

WORKDIR /app

COPY package.json ./
COPY package-lock.json ./

RUN rm -rf node_modules dist src/generated/prisma

RUN npm install

COPY . .

RUN npx prisma generate


EXPOSE 3000

CMD ["sh", "-c", "npx prisma migrate deploy && npm run dev"]
