
FROM node:22-alpine

WORKDIR /app

COPY package.json ./
COPY package-lock.json ./

RUN rm -rf node_modules dist src/generated/prisma

RUN npm install

COPY . .

# RUN npx prisma generate


EXPOSE 3000


CMD ["sh", "-c", "\
  until ping -c1 mysql > /dev/null 2>&1; do \
    echo 'Waiting for MySQL service to be reachable...'; \
    sleep 1; \
  done; \
  \
  npx prisma generate && \
  npx prisma migrate deploy && \
  npm run dev && \
  npm prisma generate \
"]
